# Generated by Django 6.0.5 on 2026-05-18 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilNutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('especialidad', models.CharField(blank=True, help_text='Ej: Nutrición clínica, deportiva, pediátrica', max_length=100, verbose_name='Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email_profesional', models.EmailField(blank=True, max_length=254, verbose_name='Email profesional')),
                ('numero_colegiatura', models.CharField(blank=True, max_length=50, verbose_name='Número de colegiatura')),
                ('direccion_consultorio', models.TextField(blank=True, verbose_name='Dirección del consultorio')),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')], default='habilitado', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Nutricionista',
                'verbose_name_plural': 'Perfiles de Nutricionistas',
            },
        ),
    ]
