# Generated by Django 6.0.5 on 2026-05-20 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de inicio de la cita', verbose_name='Fecha y hora')),
                ('duracion_minutos', models.PositiveIntegerField(default=45, help_text='Duración estimada de la consulta en minutos', verbose_name='Duración (minutos)')),
                ('tipo', models.CharField(choices=[('primera_consulta', 'Primera Consulta'), ('seguimiento', 'Seguimiento'), ('control', 'Control'), ('evaluacion', 'Evaluación')], default='seguimiento', max_length=20, verbose_name='Tipo de consulta')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='programada', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, help_text='Breve descripción del motivo de la cita', verbose_name='Motivo de la consulta')),
                ('notas_consulta', models.TextField(blank=True, help_text='Observaciones, diagnóstico o notas redactadas durante la consulta', verbose_name='Notas clínicas')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo de la consulta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora', 'estado'], name='citas_cita_fecha_h_e91b0d_idx')],
            },
        ),
    ]
